DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS CONSUMO;

CREATE TABLE CONSUMO (
    ID_CONSUMO INTEGER IDENTITY PRIMARY KEY,
    ID_CLIENTE INTEGER NOT NULL
    ELECTRODOMESTICO VARCHAR(40) NOT NULL,
    HORAS_USO INTEGER NOT NULL,
    HORA_CONSUMO TIME NOT NULL,
);

CREATE TABLE CLIENTES (
    ID_CLIENTE INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    TEL VARCHAR(20) NOT NULL,
    PAIS VARCHAR(255) NOT NULL
);

CREATE TABLE PRECIOS (
    HORA_CONSUMO INTEGER IDENTITY PRIMARY KEY,
    PRECIO_LUZ_HORA FLOAT NOT NULL,
    
);